# Generated by Django 3.1.1 on 2020-09-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('creator', models.CharField(max_length=60)),
                ('done', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
