# Generated by Django 3.1.1 on 2020-10-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
