# Generated by Django 3.1.1 on 2020-10-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
